#!/bin/bash
set -euo pipefail
trap 'echo "  ✗ Error in $(basename "$0") at line $LINENO" >&2' ERR

echo "Creating base folders"
mkdir -p $HOME/workspace $HOME/github.com/chaCon

echo "Checking for ssh key"
if ls $HOME/.ssh | grep -q "chacon"; then
  echo "- SSH key found at: $HOME/.ssh/chacon"
  echo "- Add the key to GitHub. Have you done it? (y/n)"
  read answer
else
  echo "- Creating SSH key ED25519"
  ssh-keygen -t ed25519 -C "montt.octavio@gmail.com" -f $HOME/.ssh/chacon -N ""
  echo "- Add the key to GitHub. Have you done it? (y/n)"
  read answer
fi

echo "Checking for git folders"
if [[ ! -d "$HOME/workspace/notes" ]]; then
  git clone git@github.com:L-chaCon/notes.git $HOME/workspace/notes
fi
if [[ ! -d "$HOME/Documents/personal" ]]; then
  git clone git@github.com:L-chaCon/Documents.git $HOME/Documents/personal
fi

echo "Updating brew"
brew update && brew upgrade && brew cleanup
brew install tree sshs tldr ripgrep btop

echo "Checking for JetBrains font"
if ls $HOME/Library/Fonts | grep -q JetBrainsMonoNLNerdFont; then
  echo "- JetBrains Nerd Font already installed."
else
  echo "- Installing JetBrains Nerd Font..."
  brew install --cask font-jetbrains-mono-nerd-font
fi

echo "Checking Ghostty"
if ! command -v ghostty &>/dev/null; then
  echo "- Ghostty is not installed. Installing Ghostty..."
  brew install --cask ghostty
else
  echo "- Ghostty is already installed."
fi
