#!/bin/bash
set -euo pipefail
trap 'echo "  ✗ Error in $(basename "$0") at line $LINENO" >&2' ERR

echo "Checking ZSH"
if ! command -v zsh &>/dev/null; then
  echo "- ZSH is not installed. Installing ZSH..."
  brew install zsh
else
  echo "- ZSH is already installed."
fi

echo "Installing command line tools"
brew install fzf fd bat git-delta lsd starship zoxide

mkdir -p $HOME/.zsh
echo "Checking Zsh Auto Suggestions"
if [[ ! -d "$HOME/.zsh/plugins/zsh-autosuggestions" ]]; then
  echo "- Auto Suggestion is not installed. Installing Auto Suggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/plugins/zsh-autosuggestions
else
  echo "- Auto Suggestion is already installed."
fi

echo "Checking Zsh Syntax Highlighting"
if [[ ! -d "$HOME/.zsh/plugins/zsh-syntax-highlighting" ]]; then
  echo "- Syntax Highlighting is not installed. Installing Syntax Highlighting..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting $HOME/.zsh/plugins/zsh-syntax-highlighting
else
  echo "- Syntax Highlighting is already installed."
fi

echo "Checking Git fzf"
if [[ ! -d "$HOME/.fzf-git.sh" ]]; then
  echo "- Git fzf is not installed. Installing Git fzf..."
  git clone https://github.com/junegunn/fzf-git.sh.git $HOME/.fzf-git.sh
else
  echo "- Git fzf is already installed."
fi
