#!/bin/bash
set -euo pipefail
trap 'echo "  ✗ Error in $(basename "$0") at line $LINENO" >&2' ERR

echo "Checking NeoVim"
if [[ ! -d $HOME/.local/neovim ]]; then
  echo "- Neovim is not installed. Installing Neovim..."
  current_path=$(pwd)
  git clone https://github.com/neovim/neovim.git $HOME/.local/neovim
  cd $HOME/.local/neovim
  git fetch
  xcode-select --install 2>/dev/null || true
  brew install ninja cmake gettext curl luajit pyright tree-sitter-cli
  rm -r build/
  make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local/nvim"
  sudo make install
  cd $current_path
else
  echo "- Neovim is already installed."
fi

echo "Checking Nvim Configuration"
if [[ ! -d $HOME/.config/nvim ]]; then
  echo "- Config is not installed. Installing Config..."
  mkdir -p $HOME/.config
  git clone https://github.com/L-chaCon/chaCon.nvim.git $HOME/.config/nvim
else
  echo "- Config is already installed."
fi
