#!/bin/bash
set -euo pipefail
trap 'echo "  ✗ Error in $(basename "$0") at line $LINENO" >&2' ERR

if ! command -v stow &>/dev/null; then
  echo "- Stow is not installed. Installing Stow..."
  brew install stow
else
  echo "- Stow is already installed."
fi

current_folder=$(pwd)
cat <<'EOF' >"$HOME/.zshrc"
# ==========================================
# Script Name: .zshrc
# Description: This file was automatically created
# Author: chaCon
# ==========================================

source $HOME/.chaCon
source $HOME/.local/zshrc/personal
source $HOME/.local/zshrc/fzf
source $HOME/.local/zshrc/lsd
source $HOME/.local/zshrc/brew
source $HOME/.local/zshrc/zoxie
source $HOME/.local/zshrc/opencode
EOF

echo "Creating links to dotfiles"
cd dotfiles
./install
cd $current_folder
