# CONFI CHAcON 
unbind r
bind-key r source-file ~/.tmux.conf \; display-message "chaCon"
set -g status-position bottom
set -g history-limit 50000
set -g display-time 4000
set -g mouse on
# para el screen-256color
set-option -sa terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"
# panes split a h y v
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v
# panes
unbind Up     
unbind Down   
unbind Left   
unbind Right  
unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right
bind -r Up resize-pane -U
bind -r Down resize-pane -D
bind -r Left resize-pane -L
bind -r Right resize-pane -R
# windows
set-window-option -g mode-keys vi
bind C-p previous-window
bind C-n next-window
# tmux mode
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse
# Nvim and Tmux
set-option -sg escape-time 10
set-option -g focus-events on
# PI (AI harnes)
set -g extended-keys on
set -g extended-keys-format csi-u
# Status bar
set -g status-interval 2
# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
## Vim-Tmux-navigation
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
## Tmux-fzzback
set -g @plugin 'roosta/tmux-fuzzback'
# ESTO ES UI / SEPARA
## Catppuccin Tmux
set -g @catppuccin_window_status_style "basic"
set -g status-right-length 100
set -g status-left-length 100
set -g @catppuccin_status_background "black"
set -g @catppuccin_status_module_bg_color "black"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_text_color "black"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_current_text "#[bg=green,fg=black] #W"
set -g @catppuccin_window_current_text_color "black"
set -g @catppuccin_window_current_number_color "green"
set -g @catppuccin_window_flags "text"
set -g status-left "#{E:@catppuccin_status_session}"
set -g @catppuccin_session_icon " ䷁  "
set -g @catppuccin_session_text "#[bg=magenta,fg=black] #S #[default]"
set -g @catppuccin_session_color "#{E:?client_prefix,#{E:white},bg:black#,fg:white}"
set -g status-right "#{E:@catppuccin_status_gitmux}"
set -g "@catppuccin_gitmux_icon" " 󰊢 "
set -g @catppuccin_gitmux_text "#(gitmux -cfg $HOME/.gitmux.conf \"#{pane_current_path}\")"
set -g @catppuccin_gitmux_color "cyan"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
